<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Skill;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            'Microsoft Excel',
            'Copywriting',
            'Photoshop',
            'HTML/CSS',
            'Social Media Management',
            'Data Entry',
            'Customer Service',
            'Project Management',
            'Content Writing',
            'Graphic Design',
            'Video Editing',
            'SEO',
            'WordPress',
            'PHP',
            'Laravel',
            'JavaScript',
            'React',
            'Vue.js',
            'Node.js',
            'Python',
            'Django',
            'Flask',
            'Ruby on Rails',
            'Java',
            'Spring',
            'Kotlin',
            'Swift',
            'iOS Development',
            'Android Development',
            'Flutter',
            'React Native',
            'Unity',
            'Unreal Engine',
            'Game Development',
            '3D Modeling',
            'Animation',
            'UI/UX Design',
            'Figma',
            'Adobe XD',
            'Sketch',
            'Digital Marketing',
            'Email Marketing',
            'PPC Advertising',
            'Google Analytics',
            'Facebook Ads',
            'Instagram Marketing',
            'Content Marketing',
            'Affiliate Marketing',
            'Sales',
            'Lead Generation',
            'CRM',
            'Customer Support',
            'Zendesk',
            'Intercom',
            'Help Desk',
            'Technical Support',
            'Network Administration',
            'System Administration',
            'Linux',
            'Windows Server',
            'AWS',
            'Google Cloud',
            'Microsoft Azure',
            'Docker',
            'Kubernetes',
            'Cybersecurity',
            'Penetration Testing',
            'Ethical Hacking',
            'Blockchain',
            'Cryptocurrency',
            'Smart Contracts',
            'Data Science',
            'Machine Learning',
            'Deep Learning',
            'Artificial Intelligence',
            'TensorFlow',
            'PyTorch',
            'Scikit-learn',
            'Pandas',
            'NumPy',
            'Matplotlib',
            'Data Visualization',
            'Tableau',
            'Power BI',
            'SQL',
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'Firebase',
            'REST APIs',
            'GraphQL',
            'Git',
            'GitHub',
            'Jira',
            'Agile',
            'Scrum',
            'Product Management',
            'Business Development',
            'Financial Analysis',
            'Accounting',
            'Bookkeeping',
            'QuickBooks',
            'Xero',
            'Legal Writing',
            'Contract Law',
            'Intellectual Property',
            'Human Resources',
            'Recruiting',
            'Talent Acquisition',
            'Employee Relations',
            'Translation',
            'Transcription',
            'Proofreading',
            'Editing',
            'Ghostwriting',
            'Creative Writing',
            'Technical Writing',
            'Grant Writing',
            'Resume Writing',
            'Cover Letter Writing',
            'Public Speaking',
            'Presentation Skills',
            'Negotiation',
            'Teamwork',
            'Leadership',
            'Time Management',
            'Problem Solving',
            'Critical Thinking',
            'Communication',
            'Emotional Intelligence',
            'Adaptability',
            'Creativity',
            'Innovation',
            'Photography',
            'Videography',
            'Music Production',
            'Audio Editing',
            'Podcasting',
            'Voice Acting',
            'Illustration',
            'Logo Design',
            'Brand Identity',
            'Print Design',
            'Fashion Design',
            'Interior Design',
            'Architecture',
            'CAD',
            'Tutoring',
            'Coaching',
            'Mentoring',
            'Event Planning',
            'Wedding Planning',
            'Catering',
            'Baking',
            'Cooking',
            'Personal Training',
            'Yoga Instruction',
            'Meditation',
            'Mindfulness',
            'Life Coaching',
            'Career Coaching',
            'Financial Planning',
            'Investment Strategy',
            'Real Estate',
            'Property Management',
            'E-commerce',
            'Shopify',
            'WooCommerce',
            'Magento',
            'Dropshipping',
            'Amazon FBA',
            'eBay Selling',
            'Etsy Selling',
            'Digital Art',
            'NFTs',
            'Game Testing',
            'Software Testing',
            'Quality Assurance',
            'Automation Testing',
            'Manual Testing',
            'User Research',
            'A/B Testing',
            'Conversion Rate Optimization',
            'Growth Hacking',
            'Public Relations',
            'Media Relations',
            'Crisis Management',
            'Market Research',
            'Survey Design',
            'Statistical Analysis',
            'SPSS',
            'R',
            'MATLAB',
            'SAS',
            'Excel VBA',
            'Google Sheets',
            'Airtable',
            'Notion',
            'Trello',
            'Asana',
            'Slack',
            'Microsoft Teams',
            'Zoom',
            'Google Meet',
            'Webflow',
            'Bubble',
            'Adalo',
            'Zapier',
            'Integromat',
            'API Integration',
            'Web Scraping',
            'Data Mining',
            'Big Data',
            'Apache Spark',
            'Hadoop',
            'Data Warehousing',
            'ETL',
            'Business Intelligence',
            'Data Governance',
            'Risk Management',
            'Compliance',
            'GDPR',
            'CCPA',
            'HIPAA',
            'Legal Research',
            'Paralegal Services',
            'Virtual Assistant',
            'Executive Assistant',
            'Administrative Support',
            'Data Entry Clerk',
            'Typing',
            'Telemarketing',
            'Cold Calling',
            'Appointment Setting',
            'Customer Retention',
            'Upselling',
            'Cross-selling',
            'Account Management',
            'Salesforce',
            'HubSpot',
            'Zoho CRM',
            'Pipedrive',
            'Freshdesk',
            'LiveChat',
            'Chatbot Development',
            'Dialogflow',
            'Microsoft Bot Framework',
            'Rasa',
            'Voice User Interface Design',
            'Alexa Skills Kit',
            'Google Assistant',
            'Siri Shortcuts',
            '3D Printing',
            'CNC Machining',
            'Laser Cutting',
            'Welding',
            'Woodworking',
            'Gardening',
            'Landscaping',
            'Home Repair',
            'Plumbing',
            'Electrical Wiring',
            'Painting',
            'Carpentry',
            'Masonry',
            'HVAC',
            'Appliance Repair',
            'Auto Repair',

        ];

        foreach ($skills as $skill) {
            Skill::create(['name' => $skill]);
        }
    }
}
